# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tripme
    ports:
      - 5432:5432
    volumes:
      - ./path/to/report/folder:/docker-entrypoint-initdb.d/
